{% set name = "azure-cli-telemetry" %}
{% set version = "1.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: d922379cda1b48952be75fb3bd2ac5e7ceecf569492a6088bab77894c624a278

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    - applicationinsights >=0.11.1,<0.12
    - portalocker >=1.6,<3

test:
  imports:
    - azure
    - azure.cli
    - azure.cli.telemetry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-cli
  summary: Microsoft Azure CLI Telemetry Package
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  description: Microsoft Azure CLI Telemetry Package
  doc_url: https://docs.microsoft.com/en-us/cli/azure
  dev_url: https://github.com/Azure/azure-cli

extra:
  recipe-maintainers:
    - andreyz4k
