travis:
  secure:
    BINSTAR_TOKEN: Ij4FCMDvl7rrLrIyDVTxLdEcERuJoz/4+LRcswvB6dLWILDCHEnszC28Hp29ONdPo7FnCseLBagLsytkxa5U2Ty2yn135d0UPcDf/Cno2uX/s1qvxryQUr0K8wj078v6d1piOiNDsBAkFjq4TyhpiwDzVsYSAxc+yoNYmoAVeRCJTj0Jiyk1MAnvOaOOiAO/+vnc7s04eO2RzOwhbHKmL5S/c6e9fyD7E8vWNQIfO4Lnw3IrJyn+tq0h1WGije9P1x7IaoDVaT9YVOrFoAKUYQYRr9OTpdDOY0J1xDZGjAQGZRbzf25dBSchZWGSpB9wdWXhN/vKiIOGXnqNc49UlW7dBO842ASOTm+9PXWtEGx1eeyIRlurxxtVRCQpKwK/ATNIAWnNWqnrixm2eDKpee7iXAVYKrpr9Slc4KigqTvdBifvYiVZFUAQU2j7Zqr3fw33X+lAeeMlUmDIB50dUlPQzyS31RujEJqqrxrvwh6YJ+RXGIJhcmJpn14kJe+bQLKn4UGKxHAFbYq0Snf+YNChJKXKjUEd0fZSS5l9fA7bXVnHxnXKo5BV0KeOD/W7FmZV7WBnA2PksDF7I643LgCf1LGoLZ+PH+RduHyXZrnZK24S1DmLY5BkKJVrkhs0MwL3bzAmfAl9mzTwYMcN+/UWn4X33lVISY/ZFF105fY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
